"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 13:16:05.135621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('division', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contests'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_generic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('cf_handle', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('cf_handle', name=op.f('uq_users_cf_handle')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('calibration',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('a', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('b', sa.Double(), server_default=sa.text('1'), nullable=False),
    sa.Column('n_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('b > 0', name=op.f('ck_calibration_b_positive')),
    sa.CheckConstraint('n_attempts >= 0', name=op.f('ck_calibration_n_attempts_nonneg')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calibration_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_calibration'))
    )
    op.create_table('overall_rating',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Double(), nullable=False),
    sa.Column('rd', sa.Double(), nullable=False),
    sa.Column('last_practised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rd BETWEEN 45.0 AND 350.0', name=op.f('ck_overall_rating_rd_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_overall_rating_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_overall_rating'))
    )
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('problem_index', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('twin_group', sa.Integer(), nullable=True),
    sa.Column('is_special', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_editorial', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('solved_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 800 AND 3500 AND mod(rating, 100) = 0)', name=op.f('ck_problems_rating_valid')),
    sa.CheckConstraint('solved_count >= 0', name=op.f('ck_problems_solved_count_nonneg')),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], name=op.f('fk_problems_contest_id_contests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems')),
    sa.UniqueConstraint('contest_id', 'problem_index', name='uq_problems_contest_index')
    )
    op.create_index('ix_problems_rating_candidates', 'problems', ['rating'], unique=False, postgresql_where=sa.text('rating IS NOT NULL AND NOT is_special'))
    op.create_index(op.f('ix_problems_twin_group'), 'problems', ['twin_group'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_sessions_ended_after_start')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_sessions_tag_id_tags')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('uq_sessions_one_open', 'sessions', ['user_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_table('tag_prereqs',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('requires_tag_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('tag_id <> requires_tag_id', name=op.f('ck_tag_prereqs_not_self')),
    sa.ForeignKeyConstraint(['requires_tag_id'], ['tags.id'], name=op.f('fk_tag_prereqs_requires_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tag_prereqs_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'requires_tag_id', name=op.f('pk_tag_prereqs'))
    )
    op.create_table('topic_ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('rating_offset', sa.Double(), nullable=False),
    sa.Column('rd', sa.Double(), nullable=False),
    sa.Column('last_practised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rd BETWEEN 55.0 AND 150.0', name=op.f('ck_topic_ratings_rd_range')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_topic_ratings_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topic_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id', name=op.f('pk_topic_ratings'))
    )
    op.create_table('cf_submissions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_cf_submissions_problem_id_problems')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cf_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cf_submissions'))
    )
    op.create_index('ix_cf_submissions_lookup', 'cf_submissions', ['user_id', 'problem_id', 'submitted_at'], unique=False)
    op.create_table('problem_tags',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_tags_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_problem_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'tag_id', name=op.f('pk_problem_tags'))
    )
    op.create_index('ix_problem_tags_tag_problem', 'problem_tags', ['tag_id', 'problem_id'], unique=False)
    op.create_table('seen_problems',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('attempted', 'contest', 'external', 'skipped')", name=op.f('ck_seen_problems_reason_valid')),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_seen_problems_problem_id_problems')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_seen_problems_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'problem_id', name=op.f('pk_seen_problems'))
    )
    op.create_table('attempts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('slot', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_submission_id', sa.BigInteger(), nullable=True),
    sa.Column('s', sa.SmallInteger(), nullable=True),
    sa.Column('e_model', sa.Double(), nullable=True),
    sa.Column('p_cal', sa.Double(), nullable=True),
    sa.Column('problem_rating', sa.Integer(), nullable=True),
    sa.Column('effective_rating', sa.Double(), nullable=True),
    sa.Column('info_factor', sa.Double(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('key_idea', sa.Text(), nullable=True),
    sa.Column('upsolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_calibration', sa.Boolean(), sa.Computed("source = 'session' AND rated", persisted=True), nullable=False),
    sa.CheckConstraint("(source = 'session') = (session_id IS NOT NULL)", name=op.f('ck_attempts_session_iff_source')),
    sa.CheckConstraint("s IS DISTINCT FROM 1 OR source = 'contest' OR accepted_at <= started_at + interval '45 minutes'", name=op.f('ck_attempts_solve_within_45_min')),
    sa.CheckConstraint("slot IS DISTINCT FROM 'recall' OR NOT rated", name=op.f('ck_attempts_recall_unrated')),
    sa.CheckConstraint("slot IS NULL OR slot IN ('warmup', 'main', 'stretch', 'revisit', 'recall')", name=op.f('ck_attempts_slot_valid')),
    sa.CheckConstraint("source <> 'session' OR slot IS NOT NULL", name=op.f('ck_attempts_session_needs_slot')),
    sa.CheckConstraint("source IN ('session', 'self_selected', 'contest')", name=op.f('ck_attempts_source_valid')),
    sa.CheckConstraint('(scored_at IS NULL) = (s IS NULL)', name=op.f('ck_attempts_scored_iff_s')),
    sa.CheckConstraint('e_model IS NULL OR (e_model > 0 AND e_model < 1)', name=op.f('ck_attempts_e_model_range')),
    sa.CheckConstraint('info_factor > 0', name=op.f('ck_attempts_info_factor_positive')),
    sa.CheckConstraint('p_cal IS NULL OR (p_cal > 0 AND p_cal < 1)', name=op.f('ck_attempts_p_cal_range')),
    sa.CheckConstraint('s IN (0, 1)', name=op.f('ck_attempts_s_binary')),
    sa.CheckConstraint('s IS DISTINCT FROM 1 OR accepted_at IS NOT NULL', name=op.f('ck_attempts_solve_has_accept_time')),
    sa.CheckConstraint('scored_at IS NULL OR NOT rated OR e_model IS NOT NULL', name=op.f('ck_attempts_rated_has_e')),
    sa.CheckConstraint('scored_at IS NULL OR scored_at >= started_at', name=op.f('ck_attempts_scored_after_start')),
    sa.ForeignKeyConstraint(['accepted_submission_id'], ['cf_submissions.id'], name=op.f('fk_attempts_accepted_submission_id_cf_submissions')),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_attempts_problem_id_problems')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_attempts_session_id_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    op.create_index('ix_attempts_replay', 'attempts', ['user_id', 'scored_at', 'id'], unique=False, postgresql_where=sa.text('rated'))
    op.create_index('ix_attempts_session', 'attempts', ['session_id'], unique=False)
    op.create_index('uq_attempts_one_open', 'attempts', ['user_id'], unique=True, postgresql_where=sa.text('scored_at IS NULL'))
    op.create_index('uq_attempts_rated_once', 'attempts', ['user_id', 'problem_id'], unique=True, postgresql_where=sa.text('rated'))
    op.create_table('attempt_tags',
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Double(), nullable=False),
    sa.CheckConstraint('weight > 0 AND weight <= 1', name=op.f('ck_attempt_tags_weight_range')),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_attempt_tags_attempt_id_attempts')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_attempt_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('attempt_id', 'tag_id', name=op.f('pk_attempt_tags'))
    )
    op.create_table('revisits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('served_attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('related', 'recall')", name=op.f('ck_revisits_kind_valid')),
    sa.CheckConstraint("status <> 'served' OR served_attempt_id IS NOT NULL", name=op.f('ck_revisits_served_has_attempt')),
    sa.CheckConstraint("status IN ('pending', 'served', 'cancelled')", name=op.f('ck_revisits_status_valid')),
    sa.ForeignKeyConstraint(['served_attempt_id'], ['attempts.id'], name=op.f('fk_revisits_served_attempt_id_attempts')),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['attempts.id'], name=op.f('fk_revisits_source_attempt_id_attempts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revisits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisits')),
    sa.UniqueConstraint('source_attempt_id', 'kind', name='uq_revisits_source_kind')
    )
    op.create_index('ix_revisits_due', 'revisits', ['user_id', 'due_on'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###

    # Hand-written, below the autogenerated block: Alembic does not do triggers.
    # Scored attempts are immutable. Ratings, calibration and every cache are
    # rebuilt by replaying these rows, so editing s/e_model/scored_at after the
    # fact would silently contradict numbers already written elsewhere.
    op.execute(
        """
        CREATE FUNCTION prevent_attempt_score_changes() RETURNS trigger AS $$
        BEGIN
            -- OLD.scored_at IS NULL: the attempt is still open, so scoring it
            -- (the one legitimate write to these columns) must go through.
            IF OLD.scored_at IS NOT NULL AND (
                NEW.s IS DISTINCT FROM OLD.s
                OR NEW.e_model IS DISTINCT FROM OLD.e_model
                OR NEW.scored_at IS DISTINCT FROM OLD.scored_at
            ) THEN
                RAISE EXCEPTION 'scored attempt fields are immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_attempts_score_immutable
        BEFORE UPDATE OF s, e_model, scored_at ON attempts
        FOR EACH ROW EXECUTE FUNCTION prevent_attempt_score_changes()
        """
    )


def downgrade():
    # Drop the hand-written trigger and its function first: the trigger lives on
    # `attempts`, which is dropped further down.
    op.execute("DROP TRIGGER trg_attempts_score_immutable ON attempts")
    op.execute("DROP FUNCTION prevent_attempt_score_changes()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revisits_due', table_name='revisits', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('revisits')
    op.drop_table('attempt_tags')
    op.drop_index('uq_attempts_rated_once', table_name='attempts', postgresql_where=sa.text('rated'))
    op.drop_index('uq_attempts_one_open', table_name='attempts', postgresql_where=sa.text('scored_at IS NULL'))
    op.drop_index('ix_attempts_session', table_name='attempts')
    op.drop_index('ix_attempts_replay', table_name='attempts', postgresql_where=sa.text('rated'))
    op.drop_table('attempts')
    op.drop_table('seen_problems')
    op.drop_index('ix_problem_tags_tag_problem', table_name='problem_tags')
    op.drop_table('problem_tags')
    op.drop_index('ix_cf_submissions_lookup', table_name='cf_submissions')
    op.drop_table('cf_submissions')
    op.drop_table('topic_ratings')
    op.drop_table('tag_prereqs')
    op.drop_index('uq_sessions_one_open', table_name='sessions', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_table('sessions')
    op.drop_index(op.f('ix_problems_twin_group'), table_name='problems')
    op.drop_index('ix_problems_rating_candidates', table_name='problems', postgresql_where=sa.text('rating IS NOT NULL AND NOT is_special'))
    op.drop_table('problems')
    op.drop_table('overall_rating')
    op.drop_table('calibration')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('contests')
    # ### end Alembic commands ###
