"""session picks: the problem picked for a slot, before it is opened

An Attempt row only exists once the timer starts, so a picked-but-unopened
problem had nowhere to live: GET /sessions/current would have forgotten it.
This table holds exactly that hand-off, with the three invariants the flow
depends on -- stable ordering (session_id, position), at most one pick waiting
to be opened per session, and at most one attempt per pick.

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-07 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_picks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Text(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('target_probability', sa.Double(), nullable=False),
    sa.Column('p_cal', sa.Double(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opened_attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("slot IN ('warmup', 'main', 'stretch')", name=op.f('ck_session_picks_slot_valid')),
    sa.CheckConstraint('p_cal > 0 AND p_cal < 1', name=op.f('ck_session_picks_p_cal_range')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_session_picks_position_nonneg')),
    sa.CheckConstraint('replaced_at IS NULL OR replaced_at >= picked_at', name=op.f('ck_session_picks_replaced_after_picked')),
    sa.CheckConstraint('target_probability > 0 AND target_probability < 1', name=op.f('ck_session_picks_target_probability_range')),
    sa.ForeignKeyConstraint(['opened_attempt_id'], ['attempts.id'], name=op.f('fk_session_picks_opened_attempt_id_attempts')),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_session_picks_problem_id_problems')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_picks_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_picks')),
    sa.UniqueConstraint('session_id', 'position', name='uq_session_picks_position')
    )
    op.create_index('uq_session_picks_active', 'session_picks', ['session_id'], unique=True, postgresql_where=sa.text('replaced_at IS NULL AND opened_attempt_id IS NULL'))
    op.create_index('uq_session_picks_attempt', 'session_picks', ['opened_attempt_id'], unique=True, postgresql_where=sa.text('opened_attempt_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_session_picks_attempt', table_name='session_picks', postgresql_where=sa.text('opened_attempt_id IS NOT NULL'))
    op.drop_index('uq_session_picks_active', table_name='session_picks', postgresql_where=sa.text('replaced_at IS NULL AND opened_attempt_id IS NULL'))
    op.drop_table('session_picks')
    # ### end Alembic commands ###
