from datetime import datetime

from sqlalchemy import Text
from sqlalchemy.orm import Mapped, mapped_column

from model.db import db
from model._common import TZ


class Contest(db.Model):
    """A Codeforces contest (from contest.list). Catalog: safe to re-fetch."""

    __tablename__ = "contests"

    # Codeforces' own contest id, not generated by us.
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=False)
    name: Mapped[str] = mapped_column(Text)
    division: Mapped[str | None] = mapped_column(Text)
    start_time: Mapped[datetime | None] = mapped_column(TZ)
